import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import Video from "../src/components/Video";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const wsRef = React.useRef<WebSocket>();
  const connectWs = () => {
    wsRef.current = new WebSocket("ws://localhost:8080/ws");
    wsRef.current.onopen = () => {
      wsRef.current!.send("Hello from client");
    };
    wsRef.current.onmessage = (event) => {
      console.log(event.data);
    };
  };

  const sendMsg = () => {
    wsRef.current!.send(`Hello from client ${Date.now()}}`);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={connectWs}>123</button>
        <button onClick={sendMsg}>Send</button>
        <Video />
      </main>
    </div>
  );
};

export default Home;
